# Generated by Django 5.2 on 2025-07-02 12:54

import api.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=api.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('phash', models.CharField(blank=True, max_length=16, null=True)),
                ('meta', models.CharField(default='{}')),
            ],
        ),
    ]
