# Generated by Django 5.2 on 2025-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='phash',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
