# Generated by Django 5.2 on 2025-07-01 16:37

import api.models
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts_phash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creator',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='media', replace_existing=True), upload_to=api.models.upload_to),
        ),
    ]
