# Generated by Django 5.2 on 2025-06-29 20:30

import api.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts_phash'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='process_type',
            field=models.CharField(blank=True, choices=[('grayscale', 'Grayscale'), ('resolution', 'Resolution')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=api.models.upload_to),
        ),
    ]
