# Generated by Django 5.2 on 2025-06-29 20:51

import api.models
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts_process_type_alter_posts_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='django-backend-dev'), upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='posts',
            name='phash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='process_type',
            field=models.CharField(choices=[('grayscale', 'Grayscale'), ('resolution', 'Resolution')], default='grayscale', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
