# Generated by Django 5.2 on 2025-07-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_posts_creator_alter_posts_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='duplicate_group',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='posts',
            name='processing_type',
            field=models.CharField(choices=[('none', 'None'), ('grayscale', 'Grayscale'), ('resolution', 'Resolution')], default='none', max_length=20),
        ),
    ]
