# Generated by Django 5.2 on 2025-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_posts_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='processing_type',
            field=models.CharField(choices=[('none', 'None'), ('grayscale', 'Grayscale'), ('resolution', 'Resolution')], default='none', max_length=20),
        ),
    ]
