# Generated by Django 5.2 on 2025-06-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_posts_creator_remove_posts_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='process_type',
            field=models.CharField(blank=True, choices=[('grayscale', 'Grayscale'), ('resolution', 'Resolution')], max_length=20, null=True),
        ),
    ]
