# Generated by Django 5.2 on 2025-07-01 15:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_posts_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='processed_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='posts',
            name='process_type',
            field=models.CharField(choices=[('grayscale', 'Grayscale'), ('resolution', 'Resolution')], default='grayscale', max_length=20),
        ),
    ]
