services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Host port : Container port
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data # Host folder : Container folder
    command: server /data --console-address ":9001"
