version: '3.8'

services:
  minio-server:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  grayscale_worker_1:
    build:
      context: ./workers/grayscale
    ports:
      - "8001:8001"
    container_name: grayscale_worker_1
    depends_on:
      - minio-server

  grayscale_worker_2:
    build:
      context: ./workers/grayscale
    ports:
      - "8003:8001"
    container_name: grayscale_worker_2
    depends_on:
      - minio-server

  resolution_worker_1:
    build:
      context: ./workers/resolution
    ports:
      - "8002:8001"
    container_name: resolution_worker_1
    depends_on:
      - minio-server

  resolution_worker_2:
    build:
      context: ./workers/resolution
    ports:
      - "8004:8001"
    container_name: resolution_worker_2
    depends_on:
      - minio-server

volumes:
  minio_data:
