FROM python:3.10-slim
WORKDIR /app
COPY grayscale_worker.py .  
RUN pip install fastapi uvicorn opencv-python-headless numpy python-multipart
CMD ["uvicorn", "grayscale_worker:app", "--host", "0.0.0.0", "--port", "8001"]
